### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by LuigiClaudio** [michaeluno/Fetch-Tweets-Rotator-Template#1]
It sees that the script can't find jQuery as it loads before any other scripts. Does that sounds new to you?

**Comment by michaeluno** [comment]
Hi,

Maybe in `functions.php` changing this line 

``` php
    wp_enqueue_script( 'fetch-tweets-rotator-template-bxslider', plugins_url( 'rotator/asset/bxslider/jquery.bxslider.min.js', FETCHTWEETS_ROTATOR_TEMPLETE_PATH ), array(), '', true );
```

(https://github.com/michaeluno/Fetch-Tweets-Rotator-Template/blob/1.0.4/rotator/functions.php#L8)

to

``` php
    wp_enqueue_script( 
        'fetch-tweets-rotator-template-bxslider', 
        plugins_url( 'rotator/asset/bxslider/jquery.bxslider.min.js', FETCHTWEETS_ROTATOR_TEMPLETE_PATH ), 
        array( 'jquery' ), 
        '', 
        true 
    );
```

may solve your problem. 

Let me know how it turns out.

**Comment by LuigiClaudio** [comment]
That didn't solve the problem I'm afraid. I'm still getting the "jQuery is not defined" error in console. I'm using roots.io if that information may help you.

**Comment by michaeluno** [comment]
I'm not sure.

Can you try inserting this code in `function.php` of your theme not the Rotator template.

``` php
function _load_jquery() {
    wp_enqueue_script( 'jquery' );
}
add_action( 'wp_enqueue_script', '_load_jquery' );
```

**Comment by LuigiClaudio** [comment]
That didn't solve either. Mind you I'm loading jquery as expected, what I see in the source code is that the script for the rotator is loaded soon after the footer closing tag and before every other script and the jQuery library too.

**Comment by michaeluno** [comment]
Probably your theme has special handling for enqueuing scripts. Does it occur if you try with the WordPress default theme?

**Comment by LuigiClaudio** [comment]
This doesn't occur when testing the plugin using the "Twenty Fifteen" WordPress theme. Said that tho, that theme loads the scripts in the head of the page instead the theme I'd like to use the plugin loads script at the bottom of the page. Have you tried the plugin using any of the themes that load scripts and jQuery at the bottom of the page?

**Comment by michaeluno** [comment]
I've tried one called Avada and it seems to load JavaScript resources in the footer and the rotator template still works. 

Though can you try this code instead of the one posted in my initial reply?

``` php
    wp_register_script( 
        'fetch-tweets-rotator-template-bxslider',   // handle
        plugins_url( 'rotator/asset/bxslider/jquery.bxslider.min.js', FETCHTWEETS_ROTATOR_TEMPLETE_PATH ),   // src
        array( 'jquery' ),
        '',
        true
    );
    wp_enqueue_script( 'fetch-tweets-rotator-template-bxslider' );    
```

Edit: updated the code as it had a missing comma.

**Comment by LuigiClaudio** [comment]
Thanks again. No joy with that tho. Here's the link to the starter theme I'm using at the moment http://roots.io/

**Comment by michaeluno** [comment]
It seems the starter theme you refereed requires some special configurations and does not run in normal WordPress installed environment. If you have a theme for me to test that is up and ready and can be simply downloaded and installed, I'd be happy to do that.

But can you try this code instead of the one posted in my initial reply?

``` php
function registerFetchTweetsRotatorTemplateAssets() {

    wp_register_script( 
        'fetch-tweets-rotator-template-bxslider',   // handle
        plugins_url( 'rotator/asset/bxslider/jquery.bxslider.min.js', FETCHTWEETS_ROTATOR_TEMPLETE_PATH ),   // src
        array( 'jquery' ),
        '',
        true
    );      
    wp_register_style( 
        'fetch-tweets-rotator-template-bxslider-style', 
        plugins_url( 'rotator/asset/bxslider/jquery.bxslider.css', FETCHTWEETS_ROTATOR_TEMPLETE_PATH ) 
    );
    wp_enqueue_style( 'fetch-tweets-rotator-template-bxslider-style' );

}
add_action( 'wp_enqueue_scripts', 'registerFetchTweetsRotatorTemplateAssets' );

/**
 * Explicitly add scripts in the footer.
 */
function enqueueFetchTweetsRotatorTemplateAssets() {

    wp_enqueue_script( 'fetch-tweets-rotator-template-bxslider' );    

}
add_action( 'wp_footer', 'enqueueFetchTweetsRotatorTemplateAssets' );
```

Hopefully this should work for you.

**Comment by michaeluno** [comment]
@LuigiClaudio Disregard the last reply. Probably it won't work for you as I started to guess that the error is something to do with the inline jQuery script that the template inserts and your theme that loads jQuery not in the non-conflict mode. Can you post the lines causing the error?

Also try this [branch 1.0.5b](https://github.com/michaeluno/Fetch-Tweets-Rotator-Template/archive/1.0.5b.zip), which does not have inline JavaScript scripts.
